stages:
  extract_data:
    cmd: 
    - mkdir -p data/raw_data/test
    - mkdir -p data/raw_data/train
    - python3 notebooks/extract_data.py
    deps:
    - notebooks/extract_data.py
    outs:
    - data/raw_data/test/test.parquet
    - data/raw_data/train/train.parquet
  prepare:
    cmd: 
    - mkdir -p data/prepared_data/test
    - mkdir -p data/prepared_data/train
    - python3 notebooks/prepare.py data/raw_data/test data/raw_data/train
    deps:
    - data/raw_data/test/test.parquet
    - data/raw_data/train/train.parquet
    - notebooks/prepare.py
    outs:
    - data/prepared_data/test/test.pkl
    - data/prepared_data/train/train.pkl
