stages:
  extract_data:
    cmd: python notebooks/extract_data.py
    deps:
    - notebooks/extract_data.py
    outs:
    - data/raw_data/test
    - data/raw_data/train
  prepare:
    cmd: python notebooks/prepare.py data/prepared_data
    deps:
    - data/raw_data/test
    - data/raw_data/train
    - notebooks/prepare.py
    outs:
    - data/prepared_data/test
    - data/prepared_data/train
