stages:
  extract_train_data:
    cmd: python -m notebooks.extract_train
    deps:
      - notebooks/extract_train.py
    outs:
      - data/raw_data/train

  extract_test_data:
    cmd: python -m notebooks.extract_test
    deps:
      - notebooks/extract_test.py
    outs:
      - data/raw_data/test


  prepare:
    cmd: python -m notebooks.prepare
    deps:
      - data/raw_data/train.parquet
      - data/raw_data/test.parquet
      - notebooks/prepare.py
    outs:
      - data/prepared_data/train/
      - data/prepared_data/test/
